### ISSUE TITLE
Dispose of HerculesSink may immediately cancel in-flight requests to the gate without a chance to complete

### ISSUE THREAD

**Issue by iloktionov** [vostok/hercules.client#12]
This bug might prevent application crash error logs from being sent to Hercules:
https://kontur.slack.com/archives/C08DRHZTP/p1610371124113400

**Comment by HolyPrapor** [comment]
There is indeed a chance of preventing error logs from being sent to Hercules.

This happens only when Dispose is called during sending one of the batches.

The chance is higher at the start of the application because Hercules topology has not been received yet.

Proposed solutions: 
1) Consider canceled job healthy so we will retry it later.
2) Throw on cancellation after sending the batch so we will retry it later.
3) Make delayed cancellation token so there is a higher chance that we don't cancel healthy job.

First two of them won't remove `Cancelled` error from logs, but I consider the first option as the most robust.
